Vagrant.configure("2") do |config|
  config.ssh.insert_key = false                                  # Vagrant will not automatically add a keypair to the guest    

  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|                  # VM name for VB and vagrant               
    virtualbox.vm.hostname = "test-centos7"                      # hostname   
    virtualbox.vm.box = "geerlingguy/centos7"                    # image name
    virtualbox.vm.network :private_network, ip: "172.16.3.2"     # ip 

    config.vm.provider :virtualbox do |v|                        # 
      v.gui = false                                              # without gui
      v.memory = 1024                                            # memory
      v.cpus = 1                                                 # CPU
    end

  # Python3 for ansible

    config.vm.provision "shell", inline: <<-SHELL                
        yum update
        yum install -y python3
      SHELL
  end

end