Vagrant.configure("2") do |config|
  config.ssh.insert_key = false


  NodeCount = 3

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "ceph-node-#{i}" do |cn|
      cn.vm.box = "geerlingguy/centos7"
      cn.vm.hostname = "kworker#{i}.example.com"
      cn.vm.network "private_network", ip: "172.42.42.10#{i}"
      cn.newdisk.size = 100 * 1024 # size in megabytes
      cn.newdisk.path = "ceph-node-1.vdi"
      cn.vm.provider "virtualbox" do |v|
        v.name = "ceph-node-#{i}"
        v.memory = 2048
        v.cpus = 1
      end
      config.vm.provision "shell", inline: <<-SHELL
        yum update
        yum install -y python3
        yum install -y ansible
        
      SHELL
    end
  end
end

