Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # ceph-node-1.
  config.vm.define "ceph-node-1" do |cn1|
    cn1.vm.hostname = "ceph-node-1"
    cn1.vm.box = "geerlingguy/centos7"
    cn1.vm.network :private_network, ip: "172.16.3.21"
    cn1.newdisk.size = 100 * 1024 # size in megabytes
    cn1.newdisk.path = "ceph-node-1.vdi"
    
    
    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
      
    end
  end

  # ceph-node-2.
  config.vm.define "ceph-node-2" do |cn2|
    cn2.vm.hostname = "ceph-node-2"
    cn2.vm.box = "geerlingguy/centos7"
    cn2.vm.network :private_network, ip: "172.16.3.22"
    cn2.newdisk.size = 100 * 1024 # size in megabytes
    cn2.newdisk.path = "ceph-node-2.vdi"    
    
    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
      
    end
  end

  # ceph-node-3.
  config.vm.define "ceph-node-3" do |cn3|
    cn3.vm.hostname = "ceph-node-3"
    cn3.vm.box = "geerlingguy/centos7"
    cn3.vm.network :private_network, ip: "172.16.3.23"
    cn3.newdisk.size = 100 * 1024 # size in megabytes
    cn3.newdisk.path = "ceph-node-3.vdi" 
    
    
    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
      
    end
  end

  # Python3 for ansible

    config.vm.provision "shell", inline: <<-SHELL
        yum update
        yum install -y python3
        yum install -y ansible
        
      SHELL

end

